### ISSUE TITLE
I would like to use an artifact repository for native libs

### ISSUE THREAD

**Issue by mliebelt** [scijava/native-lib-loader#10]
I would like to use your tool, but I an not sure if you support the following setup. Here is a rough sketch what I want to have:

* Organize your native libs (e.g. Windows DLL) as a Maven artifact. (have done that already)
* Declare it as a dependency for your project. (easy)
* Get the real artifact and ensure that it is "included in the load path". Your tool could here provide a solution.
* Start your application, and ensure, that the artifact is loaded properly.

Do you support a process like that? How could the third step done in your context? Is it possible to rename an artifact? Currently, the DLL is renamed when uploading to a normalized name like `<artifact-id>-<version-nr>.dll`.

**Comment by ctrueden** [comment]
The main purpose of native-lib-loader is to extract native libraries from inside JAR files present on the runtime classpath, so that they can be dynamically loaded.

If you have published your platform-specific native libraries as Maven artifacts already, then there is no need to unpack anything, and hence I am not sure what benefit you would gain from using native-lib-loader.

It sounds like all you need is to re-rename the normalized DLL back to the expected name in your application structure. This strikes me as more of a deployment issue: how do you structure your application? Where do you put the native library(ies)?

One option in your Maven build would be to use the Maven Assembly plugin + Maven Dependency plugin ([dependency:copy](https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html) goal) to create Maven JAR artifacts that bundle your desired native library(ies) in a directory structure matching what native-lib-loader wants.

Actually, in general, I think deployment is one of the trickiest parts of mixed Java/native applications, because you have to somehow ensure your native libraries are present on the `java.library.path`. Otherwise, `System.loadLibrary` will not work, which greatly complicates handling of dependencies... I don't have a good solution to this issue in general.

**Comment by ctrueden** [comment]
@mliebelt I assume my response above answers your questions? If not, please feel free to reopen!
