### ISSUE TITLE
template code for loading XD

### ISSUE THREAD

**Issue by jjYBdx4IL** [scijava/native-lib-loader#14]
Hello!

Could you please wrap the IOException inside a RuntimeException or some other unchecked Exception? UnsatisfiedLinkError from System.loadLibrary isnt checked either, so it would be nice to have sth like

    static {
            NativeLoader.loadLibrary("jniaccess");
    }

instead of

    static {
        try {
            NativeLoader.loadLibrary("jniaccess");
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
    }

at the beginning of each class.

Maybe call that function "loadLibrary2".

TY!

p.s. if you don't have the time, I may supply a pull request.

**Comment by ctrueden** [comment]
I appreciate that it would make invocation in a static initializer more succinct. However, changing this would break backwards compatibility, and I am not convinced it is actually better. The checked exception is nice to encourage developers to properly handle the exception, rather than punting it. Otherwise, your class will not initialize properly when the native library cannot load.

**Comment by jjYBdx4IL** [comment]
Checked exceptions are there to react programmatically to error conditions. There is good reason why System.loadLibraray throws the UNchecked exception UnsatisfiedLinkError. I can't think of any situation where it's useful to react to a missing libraray in code.

**Comment by ctrueden** [comment]
Well, like I said, please feel welcome to file a PR adding `loadLibraryUnchecked` that has the behavior you seek, and I will merge it straight away.
