### ISSUE TITLE
NativeLoader.loadLibrary("abc") is not doing any extraction and neither uses META-INF/lib/linux_64 etc paths

### ISSUE THREAD

**Issue by jjYBdx4IL** [scijava/native-lib-loader#15]
The console tells me it cannot find resource libabc.so. Using the debugger, it does not even construct any paths/try any other locations.

**Comment by jjYBdx4IL** [comment]
I added a fallback that is working, to demonstrate the issue:

    static {
        try {
            NativeLoader.loadLibrary("jniaccesswithlibloader");
        } catch (IOException ex) {
            System.out.println("native loader failed, trying manual load");
            try {
                //throw new RuntimeException(ex);
                File f = new File(JNIAccessWithLibLoader.class.getResource("/META-INF/lib/linux_64/libjniaccesswithlibloader.so").toURI());
                System.load(f.getPath());
            } catch (URISyntaxException ex1) {
                throw new RuntimeException(ex1);
            }
        }
    }

**Comment by ctrueden** [comment]
Thanks for the report. I'm sorry to say I don't have time to help dig into this issue over the summer, since I am way overcommitted. You should create an [MCVE](http://stackoverflow.com/help/mcve) regardless, to help others diagnose and fix this problem. And ideally there should be a unit/integration test which exercises this scenario and proves that it works the way we/you want it to.

Pull requests improving the behavior here are very welcome.

**Comment by codefish1** [comment]
I've had the same issue today.  Looking at the code it would seem it's never worked.

When using the loadLibrary it doesn't attempt to work out the platform or architecture to use in the libpath, nor even attempt to use "META-INF/lib"

**Comment by g3force** [comment]
I found the solution to this problem. Instead of NativeLoader, use:
`NativeLibraryUtil.loadNativeLibrary(<current class>, "library-vvv");`

**Comment by ptwohig** [comment]
Seconded.  I see the same thing when following the README instructions NativeLoader.loadLibrary("foo").  It seems like stepping through the code you it will just attempt to load "libfooldylib" and won't even pass the preceding "/" to actually find it on the class path.

I don't know this ever worked at all.

**Comment by ctrueden** [comment]
So what should the README say to be correct? `NativeLibraryUtil.loadNativeLibrary(<current class>, "awesome");`? Could someone confirm and file a small PR (using GitHub's Edit button is fine)?

**Comment by ptwohig** [comment]
If I get some time in the next few days, I will.

**Comment by ptwohig** [comment]
I was looking to see if there's a more 'proper' fix.  I think the approach outlined by @jjYBdx4IL requires that the libs be in the same jar as the code that's loading it, if I followed your code correctly.

I wasn't sure what the intention of NativeLoader exactly was, but I'm assuming it's to facilitate some class loader resolution so you don't have to pass that class around.

**Comment by praveenkumarS7** [comment]
I didn't get .SO included in jar.
How to do this?

**Comment by Xanthorapedia** [comment]
@codefish1 Hi David, sorry for the really delayed reply. We have recently made some changes to the loading mechanism. `NativeLoader` now should guarantee to search the path for platform-specific libraries. Does your problem persist?

**Comment by codefish1** [comment]
I've switched jobs since and don't have access to the example I was playing with to test this out.




Thanks for looking into it though.




Get Outlook for Android







On Mon, Oct 22, 2018 at 10:47 PM +0100, "Xanthorapedia" <notifications@github.com> wrote:












@codefish1 Hi David, sorry for the really delayed reply. We have recently made some changes to the loading mechanism. NativeLoader now should guarantee to search the path for platform-specific libraries. Does your problem persist?

**Comment by Xanthorapedia** [comment]
@codefish1 Sounds good!

**Comment by Xanthorapedia** [comment]
@jjYBdx4IL Hi, this problem should have been fixed by our recent changes. Only that we now recommend putting the native library in `natives/`. But for backward compatibility, `NativeLoader` will still search paths such as `META-INF/lib/<platform>/` and the root (this was how the old version actually work).

**Comment by Shaquu** [comment]
I believe problem is solved. Please close the issue.
