### ISSUE TITLE
Customisation of location for extraction and library name

### ISSUE THREAD

**Issue by rleigh-codelibre** [scijava/native-lib-loader#19]
Hi,

I'm looking to remove the need for the bioformats turbojpeg fork of the codebase, and limit it to just providing a jar containing the builds of the native libraries.  However, I've hit a bit of a snag.  Internally, turbojpeg runs `System.loadLibrary("turbojpeg")`, and we currently comment it out so that the library already loaded with native-lib-loader is used and this is a no-op.  That's the single code change in the fork.  To improve inter-operability with the upstream release, I'd like to be able to use the upstream jar directly.

What I'd like to do is set `java.library.path` so that the `loadLibrary` call works transparently.  However, this is confounded by native-lib-loader using a temporary filename with a random suffix, e.g `/tmp/libturbojpeg7478664231361760594.so`.  What I'd like to be able to do here is extract to `{tmpdir}/{random_dirname}/{libraryname}` and add `{tmpdir}/{random_dirname}` to the library path.  Would that make sense?

Looking at `BaseJniExtractor` some of the behaviour, i.e. the directory to use and the naming policy is hardcoded.  Would it be possible to make this configurable somehow, so that we can extract to a temporary directory of our choice, and skip the use of a random suffix in the filename?  Or would it be simpler for us to reimplement this directly and not use native-lib-loader at all?

Thanks,
Roger

**Comment by ctrueden** [comment]
Sorry for the delay in reply. I definitely think we should work together to make native-lib-loader work better. Making it configurable seems OK. You would need to know the `{random_dirname}` in advance of spinning up the JVM, though. How do you plan to accomplish that?

For what it's worth, for ImageJ, we are planning to drop the native ImageJ launcher in favor of a pure-Java SciJava launcher. More later!

**Comment by ctrueden** [comment]
@rleigh-codelibre I spoke with @Xanthorapedia and he believes that the merge of #20 will address this issue. I am working on doing that merge, but there are some conflicts and cleanup I need to address. The branch also uses Java-8-specific API, which will cause native-lib-loader to require Java 8+ henceforth. Based on your recent Bio-Formats usage analysis and suggestion to raise the codebase to Java 8 soon, I am guessing this would be OK? But if not, let me know and I can remove the Java-8-isms from the PR before merging it. Regardless, I will ping back here again after #20 is merged, so that you can take a look and let us know whether this issue here is resolved too.

**Comment by rleigh-codelibre** [comment]
@ctrueden Thanks, I'll be happy to give it a try once it's merged.

I'm not aware of exactly when the OME team will move to Java 8 and other than making the suggestion I have no say in that, so it might well be that it would need to be Java 7 for the time being.  I should mention that my contract with the OME team ends at the end of the month, but I will still be keeping an eye on stuff like this, and I'll certainly test this and open a PR to use the update lib loader once I've successfully tested it.

Kind regards,
Roger

**Comment by ctrueden** [comment]
Ah, forgot to ping back until now. #20 was merged back in July. Since then, new versions of native-lib-loader have been released. @rleigh-codelibre If this is issue is still relevant for you, please feel welcome to try it out. In the meantime, I'll close this issue, but you are welcome to reopen if there is more work still needing to be done on this front.

**Comment by rleigh-codelibre** [comment]
Super, thanks @ctrueden .  This was related to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/160 and I've also opened https://github.com/libjpeg-turbo/libjpeg-turbo/issues/315 as well.

Might potentially be possible to update the turbojpeg fork in the interim though.  I'll have to do some testing.
